[global]
mraauthor=["jotego"]

[parse]
sourcefile=[ "exedexes.cpp" ]

[buttons]
names=[ { names="Shot,Bomb"} ]

[ROM]
regions = [
    { name="maincpu" },
    { name="audiocpu",   start="SND_START"  },
    { name="tilerom",    start="MAP_START"  },
    { name="chars",      start="CHAR_START", reverse=true },
    { name="16x16tiles", start="SCR1_START", width=16, reverse=true, no_offset=true  },
    { name="32x32tiles", start="SCR2_START" },
    { name="sprites",    start="OBJ_START", width=16, reverse=true, no_offset=true  },
    { name="proms",      start="PROM_START" }
]

order = [
    "maincpu", "audiocpu", "tilerom", "chars", "16x16tiles", "32x32tiles",
    "sprites", "proms"
]
