[parse]
sourcefile=[ "simpsons.cpp", "parodius.cpp" ]


[buttons]
names = [
    { names="Attack,Jump", machine="simpsons" },
    { names="shoot,missile/bell,power-up", machine="parodius" },
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[header]
info = """ Header to identify the PCB type
        Byte 0 = 0 - The Simpsons
                 1 - Parodius
"""
data = [
    { machine="simpsons", offset=0, data="00" },
    { machine="parodius", offset=0, data="01" },
]

[ROM]
regions = [
    { name="maincpu",  sequence=[0,2,1,3], machine="simpsons" }, # First 32kB go to $8000, the rest are banked at $6000
    { name="maincpu",  machine="parodius" },
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="k053260",  start="PCM_START", rename="pcm", machine="simpsons" },
    { name="k053260",  start="PCM_START", rename="pcm", machine="parodius", sequence=[0,0] },
    { name="k052109",  start="JTFRAME_BA2_START", width=32, rename="tiles" }, # tiles
    { name="k053246",  start="JTFRAME_BA3_START", width=64, rename="obj", machine="simpsons" }, # sprites
    { name="k053245",  start="JTFRAME_BA3_START", width=32, rename="obj", machine="parodius" }, # sprites
    { name="eeprom",   skip=true }
]

order = [ "maincpu", "audiocpu", "pcm", "tiles", "obj" ]

# Skips the RAM check
patches = [{ setname="simpsons", offset=0x787fb, data="68 00 a9" }, # jump from 88fb to 88a7
           # skip sound RAM/ROM test
           { setname="parodius", offset=0x80011, data="00 00 00" },
           { setname="parodius", offset=0x805e6, data="00 00 00" },
           { setname="parodius", offset=0x805f8, data="00 00"    },
           { setname="parodius", offset=0x8060d, data="00 00 00" },
           { setname="parodius", offset=0x80615, data="00 00 00" },
    ]
