[parse]
sourcefile=[ "namcos1.cpp" ]
skip = { machines=[
    "shadowld",
    "dspirit",
    "quester",
    "pacmania",
    "galaga88",
    "berabohm",
    "mmaze",
    "rompers",
    "ws",
    "boxyboy",
    "tankfrce",
] }

[buttons]
names=[
    { machine="splatter", names="Attack,Jump" },
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu", width=16, reverse=true  },
    { name="sub", width=16, reverse=true  },
    { name="sub", setnames=[ "fround", "froundl" ], skip = true },
    { name="data"  },
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="fixed",    start="JTFRAME_BA2_START" },
    { name="tiles",    start="SCR_START", width=32 },
    { name="gfxrom",   start="JTFRAME_BA3_START", width=32 },
    { name="k007232"  },
    { name="upd"  }
]

order = [
    "maincpu", "sub", "data", "audiocpu",
    "k007232", "upd",
    "fixed", "tiles", "gfxrom"
]

# patches = [
#     # skip ROM check
#     { setname="fround", offset=0x1058, data="12 11" }
# ]