[parse]
sourcefile=[ "twin16.cpp" ]
parents= [
    {name="mia",description="Missing in Action"},
    {name="cuebrick",description="Cuebrick"}
]
skip = { machines=[
    "fround",
] }

[buttons]
names=[
    { machine="devilw", names="Power up,Shoot,Jump" },
    { machine="vulcan", names="Special power,Shoot,Missile" },
    { machine="mia",  names="Knife, Weapon, Weapon select" },
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu", width=16, reverse=true  },
    { name="sub",     width=16, reverse=true  },
    { name="data"  },
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="fixed",    start="JTFRAME_BA2_START" },
    { name="data",     start="SCR_START", width=32 },
    { name="gfxrom",   start="JTFRAME_BA3_START", width=32 },
    { name="gfxrom",   skip=true, setname="cuebrickj" },
    { name="k007232"  },
    { name="upd"  }
]

order = [
    "maincpu", "sub", "data", "audiocpu",
    "k007232", "upd",
    "fixed", "gfxrom"
]

patches = [
    # skip ROM check
    { setname="fround", offset=0x1058, data="12 11" }
]