[global]
author=["jotego"]

[buttons]
names=[
	{ machine="flstory",  names="Shot,Jump" },
	{ machine="onna34ro", names="Hit,Throw" },
	{ machine="rumba",    names="Chop,Throw"},
	# buttons 4/5/6 do not seem to be used
	{ machine="victnine", names="Button 1,Button 2,Button 3,Button 4,Button 5,Button 6" },
]

[parse]
sourcefile=[ "flstory.cpp" ]
debug={ machines=[
	# "nycaptor"
]}

[dipsw]
rename=[
	{ name="Attract Sound on Title Screen",to="Attract Sound" },
	{ name="Invulnerability (Cheat)",      to="Invulnerability"},
	{ name="Copyright String",             to="Release year", values=["hide","show"] }
]

[header]
info="""

		byte 0: PCB id
		byte 1: 0 == same orientation as flstory
		        1 == flipped both XY
		        2 =  flipped only Y - to be tested -
		byte 2: 0 == MCU enabled
		        1 == MCU disabled
		byte 3: 0 == coins are active low
		        1 ==                  high
		byte 4: 0 == GFX config register at $DF03
		        1 == GFX config register at $DCE0
		byte 5: 0 == use priority RAM
		        1 == obj always have priority
		byte 6: 0 == 4-bit palette for background
		        1 == 3-bit palette
		       0? == 2 buttons
		       1? == 6 buttons
		      0?? == 4 banks for sprites
		      1?? == 2 banks
"""
fill=0
PCBs = [
	{ machine ="flstory"  },
	{ machine ="onna34ro" },
	{ machine ="rumba"    },
	{ machine ="victnine" },
]
data = [
	{ pcb_id=true, offset=0 },
	{ machines=["onna34ro"],            data="01", offset=1 },
	{ machines=["rumba"],               data="02", offset=1 },
	# Disable MCU
	{ setname="onna34roa",              data="01", offset=2 },
	# coins active high/low
	{ setname="rumba",                  data="01", offset=3 },
	# GFX config register location
	{ machines=["rumba","victnine"],    data="01", offset=4 },
	# Layer priority
	{ machines=["rumba","victnine"],    data="01", offset=5 },
	# Palette
	{ setname="victnine",               data="07", offset=6 },
]

[ROM]
regions = [
	{ name="maincpu"                             },
	{ name="audiocpu", start="JTFRAME_BA1_START" },
	{ name="gfx1",     start="JTFRAME_BA2_START", width=16, sequence=[0,4,1,5,2,6,3,7] },
	{ name="gfx1",     start="JTFRAME_BA2_START", width=16, sequence=[0,2,1,3,0,2,1,3], machine="rumba" },
	{ name="bmcu:mcu", start="JTFRAME_PROM_START"},
]

order=["maincpu","audiocpu","gfx1","bmcu:mcu"]