name: Verilator linter

on:
  workflow_dispatch:
  repository_dispatch:
    types: rebuild
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # runs every night
jobs:
  linter_cores:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        token: ${{secrets.PAT}} # Personal Access Token, must be defined in the repo's secrets
    - id: linter
      run: |
        # pwd will be: /home/runner/work/jtcores/jtcores
        docker run --network host -v `pwd`:/jtcores jotego/linter /jtcores/modules/jtframe/devops/lint-all.sh
